version: "3.3"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
