version: "3.3"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    networks:
      - appnet

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
