version: "3.3"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - appnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  grafana-data:
